name: 'Build image'
description: 'Build docker image'
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: docker:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: doctor/who:latest
